### ISSUE TITLE
fitSize is not a function

### ISSUE THREAD

**Issue by Lacroute** [rveciana/d3-composite-projections#12]
Hi,

I discovered a bug I think, I cannot use fitSize on `geoConicConformalFrance`

Open your devtools and try to uncomment line 4.
Here the jsfiddle to test > https://jsfiddle.net/x0z94gmc/3/

Maybe I didn't use it the right way?

**Comment by rveciana** [comment]
Have you tried the 1.1.0 version? The link in the fiddle is the 1.0.0, where fitSize was still not implemented

**Comment by Lacroute** [comment]
I did not realize that I didn't have the right version, I copied the cdn url in the readme, wich is a link to 1.0... I close this one sorry!
