### ISSUE TITLE
Cannot read property 'polygonStart' of undefined

### ISSUE THREAD

**Issue by Lacroute** [rveciana/d3-composite-projections#13]
d3: v4.5.0
d3-geo-projection: v1.2.1
d3-composite: v1.1.0

This one made me mad and I couldn't reproduce it on jsfiddle because of the wrong version number...

So I can't use `geoProject` on `geoConicConformalFrance()`

Here is a link to test > https://jsfiddle.net/x0z94gmc/6/

**Comment by rveciana** [comment]
I updated the library. The version 1.1.1 works with your example
