### ISSUE TITLE
block about Europe composite is not working anymore

### ISSUE THREAD

**Issue by espinielli** [rveciana/d3-composite-projections#4]
When I browse [Europe composite's block](http://bl.ocks.org/rveciana/4bcc5750c776c22ffda6) it does not show any map up.
In the console I get
```
Refused to execute script from 'https://raw.githubusercontent.com/rveciana/d3-composite-projections/master/src/conicConformalEurope-proj.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
Uncaught TypeError: d3.geo.conicConformalEurope is not a function
```
I think this is sue to the way github serves raw files, i.e. as text, in order to avoid sniffing, see [this SO item](http://stackoverflow.com/a/18049842/963575)

There is still one use of `raw.githubusercontent.com` to be changed in the `index.html`

I forked and fixed it [here](http://bl.ocks.org/espinielli/715229536cdba1fdac9a)

**Comment by rveciana** [comment]
Thank you. It works in the devices where I've tested it, but I have changed the block anyway so nobody has problems. bl.ocks.org has some cache that delays the refresh, but the new version will appear soon.
