### ISSUE TITLE
Rebuild conicConformalSpain-proj.min.js

### ISSUE THREAD

**Issue by martgnz** [rveciana/d3-composite-projections#5]
Please, can you rebuild the file?

@lukasappelhans did a PR that is not included there yet (but in `composite-projections`).

**Comment by rveciana** [comment]
The error is in composite-projections or in conicalConformalSpain?

**Comment by martgnz** [comment]
In conicConformalSpain. The [fix](https://github.com/rveciana/d3-composite-projections/commit/5e13c42cf3e70a861d1d060b29e6ef14ee370463) on composite-projections was commited three months ago. If you look up the latest change to conicConformalSpain was four months ago.

**Comment by rveciana** [comment]
Done, thank you! I haven't tagged it yet, nor updated the NPM package, since I'll add a new projection soon. If you need it, I can do it.
