### ISSUE TITLE
add USA with territories represented in US Congress

### ISSUE THREAD

**Issue by micahstubbs** [rveciana/d3-composite-projections#6]
so I'm following these instructions for [generating topojson for US Congressional districts](http://stackoverflow.com/questions/14565963/topojson-for-congressional-districts)

from this shapefile data for 114th Congress from US census available at 
[ftp://ftp2.census.gov/geo/tiger/TIGER2016/CD/](ftp://ftp2.census.gov/geo/tiger/TIGER2016/CD/)  

and I realize, whoa, there are several distant lands of the US beyond Alaska and Hawaii
![screen shot 2016-08-16 at 5 23 36 am](https://cloud.githubusercontent.com/assets/2119400/17698780/d39f40d0-6371-11e6-9f08-92c0709ea4a6.png)

it would be cool to add a `d3-composite-projection` that includes the territories represented by the [non-voting members of the U.S. House of Representatives](https://en.wikipedia.org/wiki/Non-voting_members_of_the_United_States_House_of_Representatives)

American Samoa
Guam
Northern Mariana Islands
Puerto Rico
U.S. Virgin Islands

**Comment by micahstubbs** [comment]
will start working on this.  would be cool if another contributor with more knowledge were to get it working first 😄

**Comment by micahstubbs** [comment]
it looks like it should be possible to create this by forking the `Albers USA` composite projection and adding the additional geography with the same pattern used to add Alaska and Hawaii 

[https://github.com/rveciana/d3-composite-projections/blob/master/src/albersUsa-proj.js](https://github.com/rveciana/d3-composite-projections/blob/master/src/albersUsa-proj.js)

**Comment by micahstubbs** [comment]
(small) progress!  just rendered a map with the `d3-composite albersUSA` projection and a different topojson file.

I think that I need to use a topojson file that contains the small island territories I want to show.  Since the topojson file `us.json` from [this nice example] (http://bl.ocks.org/rveciana/170a76b8dc1f9cfd8b2d) doesn't have geometry for all of the islands I want to show (though strangely it does have Puerto Rico and some hard-to-identify Pacific islands). So instead I use `tl_2015_us_cd114_2pc.json` which I created with [mapshaper](http://mapshaper.org/) from the shapefile linked above.

[link to the line of code where I change the topojson file](https://github.com/micahstubbs/114th-congress-mobile-vis/blob/master/01/index.html#L53)

I already notice that the names of features vary from one topojson file to another. It also looks like the way that people represent boundaries like states also varies.  In one case the topojson is nested, in the other it is more flat with features like the state loaded on as properties.  hhhhmmm.

Next, I will try to show the boundaries on the individual congressional districts on the map.  Then, I will add the positions for one of the islands (probably `Guam`) to the composite projection and see if I can get the island on screen. 

<img width="1440" alt="screen shot 2016-08-21 at 5 52 12 pm" src="https://cloud.githubusercontent.com/assets/2119400/17841006/8e3fb88e-67c8-11e6-8b63-3221528dfa21.png">

**Comment by micahstubbs** [comment]
took a closer look at the two geographies, before compositing. I want to make sure that the islands I want to are indeed in the geography I'm using (that is, the topojson file I created from the shapefile I downloaded).  here's some screenshot prototypes that I marked up with [GIMP](https://www.gimp.org/downloads/)

**first `us.json`, the geography from the project example**
![us json](https://cloud.githubusercontent.com/assets/2119400/17843786/f6f7f512-67e6-11e6-94cb-7275e434fce9.png)  


**then `tl_2015_us_cd114_2pc.json` which is the congressional districts geography**
![congressional-district-topojson](https://cloud.githubusercontent.com/assets/2119400/17843803/2413a910-67e7-11e6-931d-ba640f785fa8.png)

**Comment by micahstubbs** [comment]
if we log out the topojson into the console, we can see it's structure

`console.log('us', us);`

![screen shot 2016-08-21 at 11 18 56 pm](https://cloud.githubusercontent.com/assets/2119400/17845323/e6287f54-67f5-11e6-99c5-be1ae0a6b1ba.png)

**Comment by micahstubbs** [comment]
so I searched this comment above Hawaii 

![screen shot 2016-09-02 at 6 07 17 pm](https://cloud.githubusercontent.com/assets/2119400/18221742/1f79cb50-7138-11e6-984b-171b2fb0b09d.png)

https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=ESRI%3A102007

and found a similiar listing for American Samoa.  progress!

http://spatialreference.org/ref/epsg/2155/

**Comment by micahstubbs** [comment]
found the docs for `projection.rotate()`

https://github.com/d3/d3-3.x-api-reference/blob/master/Geo-Projections.md#rotate

**Comment by micahstubbs** [comment]
likewise 

![screen shot 2016-09-02 at 6 14 41 pm](https://cloud.githubusercontent.com/assets/2119400/18221780/29279a00-7139-11e6-9b51-52a23f871ebe.png)

https://github.com/d3/d3-3.x-api-reference/blob/master/Geo-Projections.md#center

**Comment by micahstubbs** [comment]
learning more about standard parallels

![screen shot 2016-09-02 at 6 22 41 pm](https://cloud.githubusercontent.com/assets/2119400/18221834/4483705c-713a-11e6-860e-e6874528dce0.png)

https://github.com/d3/d3-3.x-api-reference/blob/master/Geo-Projections.md#conicConformal_parallels

![screen shot 2016-09-02 at 6 22 21 pm](https://cloud.githubusercontent.com/assets/2119400/18221832/35ea649c-713a-11e6-9a12-e30dd7bcca2f.png)

http://support.esri.com/other-resources/gis-dictionary/term/standard%20parallel

**Comment by micahstubbs** [comment]
a first effort at adding [American Samoa](https://en.wikipedia.org/wiki/American_Samoa)

got the path that shows the boundaries between the composite projections to render.  that's something!

so many parameters to tune...

https://github.com/micahstubbs/d3-composite-projections/blob/composite-usa/src/albersCompositeUsa-proj.js

![screen shot 2016-09-02 at 7 00 14 pm](https://cloud.githubusercontent.com/assets/2119400/18222054/cb12d09a-713f-11e6-93d2-c273e347b9e1.png)

**Comment by micahstubbs** [comment]
the current best effort, as an anonymous block on blockbuilder
http://blockbuilder.org/anonymous/07f95ff1b01125f8150dbad1b7f586c5#mode=sidebyside

**Comment by rveciana** [comment]
I'll take your topojson example to see all the lands. When I have an example, I'll send it!

**Comment by micahstubbs** [comment]
@rveciana that would be delightful 😄

**Comment by micahstubbs** [comment]
latest conversation, for anyone following along at home https://twitter.com/rveciana/status/772118057649074176

**Comment by rveciana** [comment]
I'll put some information here:
The projection you suggested works when changed to
`d3.geoConicConformal().center([-170, -14.267]).parallels([-24, -14]).scale(2000);`
But the result is rotated, so the islands don't have the north at the top, which can be weird:
![ne](https://cloud.githubusercontent.com/assets/2832885/18256046/464833fa-73b0-11e6-9d39-c5cae76457c4.png) The google maps, where north is the upper side of the screen look like this: https://www.google.es/maps/place/Samoa+Nord-americana/@-14.0893802,-171.8807741,8.75z/data=!4m5!3m4!1s0x71a513a364ec1003:0xa6870c9674617872!8m2!3d-13.759029!4d-172.104629
Besides, the origin I have used is the typical Natural Earth file world-50m.json, since the one you gave has a strange coast line:
![census](https://cloud.githubusercontent.com/assets/2832885/18256052/61190a56-73b0-11e6-9e44-3af03e905532.png)
Now I'll try with a latlon projection directly, because is also used: http://spatialreference.org/ref/epsg/american-samoa-1962/ and the latitude is ok to do so.
I'll post the image

**Comment by rveciana** [comment]
The platee caree projection
`d3.geoEquirectangular().rotate([172, 14]).scale(3200);`
gives this result
![latlon](https://cloud.githubusercontent.com/assets/2832885/18256202/6961306a-73b2-11e6-9afd-c1cdb865f3af.png)
which seems much better.

**Comment by rveciana** [comment]
The code:
```
<!DOCTYPE html>
<meta charset="utf-8">
<style>

.states {
  fill: #ccc;
  stroke: #fff;
}
</style>
<body>
<script src="https://d3js.org/d3-array.v1.min.js"></script>
<script src="https://d3js.org/d3-geo.v1.min.js"></script>

<script src="https://d3js.org/d3-selection.v1.min.js"></script>

<script src="https://d3js.org/d3-collection.v1.min.js"></script>
<script src="https://d3js.org/d3-dispatch.v1.min.js"></script>
<script src="https://d3js.org/d3-request.v1.min.js"></script>

<script src="http://d3js.org/topojson.v1.min.js"></script>
<script>
var width = 960,
    height = 500;


var projection = d3.geoEquirectangular().rotate([172, 14]).scale(3200);
var path = d3.geoPath()
    .projection(projection);

var svg = d3.select("body").append("svg")
    .attr("width", width)
    .attr("height", height);

svg.append("path")
  .datum({type: "Sphere"})
  .attr("d", path)
  .style("fill","#eee");
d3.json("world-50m.json", function(error, us) {

  svg.append("path")
      .attr("class", "us")
      .datum(topojson.feature(us, us.objects.countries))
      .attr("d", path)

      d3.select("svg").on("mousedown.log", function() {
  console.log(projection.invert(d3.mouse(this)));
});


});

</script>
```

**Comment by micahstubbs** [comment]
@rveciana thanks for putting the information here 😄 

using the other projection and the `world-50m.json` does look like a good idea.  since the islands of American Samoa are together only [one congressional district](https://en.wikipedia.org/wiki/American_Samoa%27s_at-large_congressional_district), we do not lose any internal administrative (congressional district) boundaries by switching the geography we use.

**Comment by rveciana** [comment]
First working version: http://bl.ocks.org/rveciana/ce5936de720ebb83aafecb35dfd9531a
Besides the Puerto Rico border, which must be fixed, do you find some error? Guam + Northern Mariana Islands are together since they are actually very close. And Puerto Rico and Virgin islands too.

**Comment by micahstubbs** [comment]
👍 will take a closer look

**Comment by micahstubbs** [comment]
by the way, thanks for introducing me to `console.info()`  
https://developer.mozilla.org/en-US/docs/Web/API/Console/info

**Comment by micahstubbs** [comment]
got the first working version running locally for my closer look.  some first impressions:

it makes sense to use one view (and one blue composition border) for the islands that are near to each other, like `Puerto Rico` and the `US Virgin Islands`. that said, now I want some method of identifying which islands belong to which named territory (as my own geography knowledge of these islands is not as good as I would like, so I cannot recognize all of them from the shape alone 😅  ).  

one solution to make individual territories distinct is a `mouseover` event that shows a tooltip.

if I log out `d, i, nodes, this` from the `mouseover` event, I get the features for all of the map. This makes sense when I remember that our map is one big SVG path element. 

![screen shot 2016-09-07 at 12 08 46 pm](https://cloud.githubusercontent.com/assets/2119400/18324953/e238b99e-74f3-11e6-94f4-8257b96a2519.png)


If I remember correctly, the way to find the specific place under the mouse cursor in `x, y` screen coordinates is to invert the projection and use the resulting `[longitude, latitude]` to determine what territory (or congressional district, in this case) the mouse is currently over.

[the d3.geo v4 docs](https://github.com/d3/d3-geo/blob/master/README.md#projection_invert) for `projection.invert(point)` 

working on figuring this part out now 😄

**Comment by micahstubbs** [comment]
one other step I'd like to do for this example, that I've overlooked so far:

> You’ll probably want to combine the TopoJSON file with the land and states features from us.json, since in most maps you’ll want to clip the congressional districts to the land boundary, and draw some additional boundary between states. That can be done by combining TopoJSON files using multiple input arguments to the topojson binary.

from [@mbostock](https://twitter.com/mbostock)'s [StackOverflow answer](http://stackoverflow.com/a/14567017/1732222) about creating a congressional district map in d3 (without territories)

**Comment by rveciana** [comment]
I've changed the block so an alert showing the district appears when a region is clicked. 
The Puerto Rico /Virgin Islands case is really complicated to separate with the topojson you passed, while with Guam/Marianas is possible.
I'll try to draw the lines, but the map is very small and I think that the result will be quite ugly.
The MikeBost0ck's solution is good too, but I don't know anything about these Congressional Districts. Do they always correspond to a county or more, or a county can be divided in different districts? If the last case doesn't happen, creating a new topojson shouldn't be too difficult.

**Comment by micahstubbs** [comment]
Good question.  The [US congressional districts](https://en.wikipedia.org/wiki/List_of_United_States_congressional_districts) are an district within a US state (and occasionally contain an entire state). The congressional districts have no formal relationship with US counties.

**Comment by micahstubbs** [comment]
creating a new topojson file will be a good learning exercise for me 😄

**Comment by micahstubbs** [comment]
when I click, I do see an alert.  nice!

![screen shot 2016-09-07 at 4 00 33 pm](https://cloud.githubusercontent.com/assets/2119400/18331498/4ff6f854-7514-11e6-9168-3f380aac4946.png)
![screen shot 2016-09-07 at 4 00 10 pm](https://cloud.githubusercontent.com/assets/2119400/18331499/516a178e-7514-11e6-84f9-09b683b167fd.png)

**Comment by micahstubbs** [comment]
ah, the way we do the data binding is the difference here.  before we had one path.  now we have many paths, with one for each district.   now this makes sense 👌 

[diff from the gist](https://gist.github.com/rveciana/ce5936de720ebb83aafecb35dfd9531a/revisions)

![screen shot 2016-09-07 at 4 06 11 pm](https://cloud.githubusercontent.com/assets/2119400/18331616/1d779d74-7515-11e6-87ba-f4e934394551.png)

**Comment by micahstubbs** [comment]
this might be useful https://github.com/bradoyler/atlas-make/tree/master/us-congress

**Comment by rveciana** [comment]
Oh, this is much better! 
http://bl.ocks.org/rveciana/57ab45aad3cda72b879a9a96498a2394

Some territories are not present, but I'll try to add them from the world-50m file. The examples will improve a lot, thank you.

**Comment by rveciana** [comment]
Finally, I'm more or less satisfied with this dataset & projection:
http://bl.ocks.org/rveciana/fe6b452c853146e674dd6dd09c1cc6e3

**Comment by micahstubbs** [comment]
very nice!  will post here when I finish the original project that inspired this feature request :-)

**Comment by rveciana** [comment]
Thank you! If people uses it, I'll be really happy.
